version: '3.8'

services:
    webserv:
        container_name: our-nginx
        image: our-nginx-image
        build:
            context: ./nginx/
        ports:
            - '80:80'
        volumes:
            - ./frontend/dist/:/var/www/cosmic-pong
